### ISSUE TITLE
Outreach Fixes

### ISSUE THREAD

**Issue by hemangandhi** [usacs/usacs.github.io#93]
We need to add the following to the outreach page:

ok there's 2 things for the outreach section that are near or immediately able to go on, and two that depends on content i don't yet have. the first two: i'd love to have little profiles of the panelists - a small photo and a one or two sentence blurb so teachers can see the diversity of people and experiences. the second is a downloadable (which i'll create) of a VCV outlined as a lesson plan. the other two are a video clip of an actual session, and teacher testimonials. also would it be possible to move the slideshow up before the student testimonials? it would be nice to break up that huge block of text.

For tabs, see the get involved page.

**Comment by hemangandhi** [comment]
Trying to assign to Diane (goldencarrots72)...

**Comment by goldencarrots72** [comment]
The slideshow is above testimonials, but theres some weirdness happening with the img sizes and the way i added prev/next buttons. Also, the img size cuts off the bottom of the indicator dots. I'm currently working on the panelist tab called "ambassadors". It's taking some time because the css files are overlapping with the new bootstrap ones im trying to put in but it's getting there. Added the tab in navigator on all html pages. I left 3 choices for hyperlinks to panelists' Linked In but idk which is most appealing.

**Comment by hemangandhi** [comment]
@goldencarrots72 updates?

**Comment by goldencarrots72** [comment]
fixed the ambassador tab thing, working on template for ambassador tab. i think ill find a different nav button for the carousel since that seems easier than figuring out why the pictures cut off on the bottom
