### ISSUE TITLE
use js to load in things instead of having a template compiler

### ISSUE THREAD

**Issue by mjrb** [usacs/usacs.github.io#97]
originally I added a template compiler so we could reuse code and not have to change the nav bar in every document. this was a good idea but probably not the correct implementation. it adds a compile stage (the user must have correct version of python) in order to commit.
my initial idea to fix this was to have then index page have an iframe for content, nav bar and footer, but heman added that we could load in the content javascript instead. this makes then nav bar slightly more complicated but i think its a better solution than the template compiler.
@Sail338 if you approve I'll probably do this during the summer at some point or you can jump in.

**Comment by hemangandhi** [comment]
Quick comment: a big benefit is that python no longer becomes necessary for testing. This would make it easier for others to contribute.

A few drawbacks are that it would be harder to bookmark/navigate since the browser history wouldn't be updated. Also, SEO would be hampered if pages need different meta-data. I can only see this impacting the outreach page if anything and I'm sure there are workarounds for
the bookmarking/linking (the JS could alter the URL with some marker query string).
